from datetime import datetime
from .log import logger
import random
from .minify_assets import minify_html

def generate_html(news, policies, econ, forex):
    now = datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')

    # Generate random colors for headlines
    def random_color():
        return f"#{random.randint(0, 0xFFFFFF):06x}"

    headline_colors1 = [random_color() for _ in news]
    headline_colors2 = [random_color() for _ in news]

    html = f"""
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <title>Waneye Financial Dashboard</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='icon' type='image/svg+xml' href='favicon.svg'>
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/gh/jellythemes/jelly-bootstrap@main/dist/jelly-bootstrap.min.css'>
    <link rel='stylesheet' href='static/style.css'>
</head>
<body>
    <canvas id='bg-canvas'></canvas>
    <div class='container my-5'>
        <div class='text-center mb-4'>
            <h1 class='display-4 fw-bold'>Waneye Financial World Overview</h1>
            <p class='text-muted' id='last-updated'><em>Last updated: {now}</em></p>
        </div>
        <div class='row g-4'>
            <div class='col-md-6'>
                <div class='card shadow-sm'>
                    <div class='card-header bg-primary text-white'>Top Financial Headlines</div>
                    <ul class='list-group list-group-flush'>
                        {''.join([f"<li class='list-group-item'><span class='headline-bullet' style='background:linear-gradient(135deg, {color1} 60%, {color2} 100%);box-shadow:0 1px 4px {color1}55;'></span><a href='{item['url']}' target='_blank'>{item['headline']}</a></li>" for item, color1, color2 in zip(news, headline_colors1, headline_colors2)])}
                    </ul>
                </div>
            </div>
            <div class='col-md-6'>
                <div class='card shadow-sm'>
                    <div class='card-header bg-info text-white'>Central Bank Rates</div>
                    <ul class='list-group list-group-flush'>
                        {''.join([f"<li class='list-group-item'><b>{item['bank']}:</b> {item['rate']}</li>" for item in policies])}
                    </ul>
                </div>
            </div>
        </div>
        <div class='row g-4 mt-2'>
            <div class='col-md-6'>
                <div class='card shadow-sm'>
                    <div class='card-header bg-success text-white'>Key Economic Data</div>
                    <ul class='list-group list-group-flush'>
                        {''.join([f"<li class='list-group-item'>{item['event']}: {item['value']} ({item['date']})</li>" for item in econ])}
                    </ul>
                </div>
            </div>
            <div class='col-md-6'>
                <div class='card shadow-sm'>
                    <div class='card-header bg-warning text-dark'>Forex CFD Quotes</div>
                    <div class='table-responsive'>
                        <table class='table table-bordered mb-0'>
                            <thead class='table-light'><tr><th>Pair</th><th>Bid</th><th>Ask</th></tr></thead>
                            <tbody>
                                {''.join([f"<tr><td>{item['pair']}</td><td>{item['bid']}</td><td>{item['ask']}</td></tr>" for item in forex])}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <footer class='text-center mt-5 text-muted'>
            <hr>
            <small>Generated by Waneye.com &mdash; Powered by JellyThemes</small>
        </footer>
    </div>
    <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js'></script>
    <script src='static/main.js'></script>
</body>
</html>
"""
    return minify_html(html)
