name: Build and Test Waneye Financial Overview (PR)

on:
  pull_request:
    branches:
      - "*"

jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Install Playwright browsers
        run: |
          playwright install chromium
      - name: Install system dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk-bridge2.0-0 \
            libdrm2 \
            libxkbcommon0 \
            libgtk-3-0 \
            libgbm1 \
            libasound2t64 \
            libxrandr2 \
            libxss1
      - name: Build static site (no deploy) - Test Mode for Fast CI/CD
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_site.py --test-mode
      - name: Check index.html generated
        run: test -f index.html
