name: Build and Test Waneye Financial Overview (PR)

on:
  pull_request:
    branches:
      - "*"
    paths:
      - '**.py'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Install Playwright browsers
        run: |
          playwright install chromium
          playwright install-deps
      - name: Build static site (no deploy) - Test Mode for Fast CI/CD
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_site.py --test-mode
      - name: Check index.html generated
        run: test -f index.html
